#!/bin/bash
source ~/scripts/colors.sh

clear

printf "IMPRESION DE UN TEXTO REGULAR...\n"
printf "${BLACK}BLACK Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${DARK_RED}DARK_RED Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${DARK_GREEN}DARK_GREEN Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${DARK_YELLOW}DARK_YELLOW Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${DARK_BLUE}DARK_BLUE Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${DARK_MAGENTA}DARK_MAGENTA Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${DARK_CYAN}DARK_CYAN Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${CYAN}CYAN Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${DARK_GRAY}DARK_GRAY Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${RED}RED Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${GREEN}GREEN Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${ORANGE}ORANGE Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${BLUE}BLUE Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${MAGENTA}MAGENTA Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${CYAN}CYAN Esto es una prueba de funcionamiento de color${DEFAULT}\n"
printf "${WHITE}WHITE Esto es una prueba de funcionamiento de color${DEFAULT}\n"

echo "\n\n"
printf "${BG_BLACK}BLACK Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_DARK_RED}DARK_RED Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_DARK_GREEN}DARK_GREEN Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_DARK_YELLOW}DARK_YELLOW Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_DARK_BLUE}DARK_BLUE Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_DARK_MAGENTA}DARK_MAGENTA Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_DARK_CYAN}DARK_CYAN Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_CYAN}CYAN Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_DARK_GRAY}DARK_GRAY Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_RED}RED Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_GREEN}GREEN Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_ORANGE}ORANGE Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_BLUE}BLUE Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_MAGENTA}MAGENTA Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_CYAN}CYAN Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"
printf "${BG_WHITE}WHITE Esto es una prueba de funcionamiento de color${BG_DEFAULT}\n"

printf "${MSG_ERROR}Este es un mensaje de ERROR${MSG_DEFAULT}\n"
printf "${MSG_WARNING}Este es un mensaje de ADVERTENCIA${MSG_DEFAULT}\n"
printf "${MSG_SUCCESS}Este es un mensaje de EXITO${MSG_DEFAULT}\n"
printf "${MSG_INFO}Este es un mensaje de INFORMACION${MSG_DEFAULT}\n"

SHOW_ERROR "ESTO ES UN ERROR DE PRUEBA"
SHOW_WARNING "ESTO ES UN ERROR DE PRUEBA"
SHOW_SUCCESS "ESTO ES MENSAJE EXITOSO DE PRUEBA"
SHOW_INFO "ESTO ES UNA INFORMACIÓN DE PRUEBA"
